name: 'Ascend school setup'
description: 'Ascend school setup recipe - installs modules and sets up config'
type: 'Content type'
recipes:
  # Can't depend on other recipes outside of this dir or core!
install:
  - ascend_school
config:
  strict: true
  import:
    ascend_school: '*'

